name: Build MPV Android
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build meson python3-pip wget unzip openjdk-17-jdk
          pip3 install requests

      - name: Build everything
        run: |
          ./buildscripts/download.sh
          ./buildscripts/buildall.sh --clean --release -n ffmpeg

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: mpv-android-apks
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
